apiVersion: v1
kind: Service
metadata:
  labels:
    app: oktasampleapi
  name: oktasampleapi
spec:
  selector:
    app: oktasampleapi
  ports:
    - name: "http"
      port: 62514
      targetPort: 80
    - name: "https"
      port: 62513
      targetPort: 443
  type: ClusterIP
