apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktasampleapi
spec:
  selector:
    matchLabels:
      app: oktasampleapi
  template:
    metadata:
      labels:
        app: okta-sample-api # the label for the pods and the deployments
    spec:
      containers:
      - name: oktasampleapi
        image: acr26025.azurecr.io/okta-sample-api:v1 # IMPORTANT: update with your own repository
        imagePullPolicy: Always
        ports:
        - containerPort: 443 # the application listens to this port
        env:
        - name: ConnectionStrings__AppConfig # the application expects to find the Azure App Configuration service connection details in this environment variable
          valueFrom:
            secretKeyRef:
              name: appcfgsecret # the name of the Kubernetes secret containing the data
              key: APPCFGCONNECTION # the key inside the Kubernetes secret containing the data
        resources:
          requests: # minimum resources required
            cpu: 250m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 500m
            memory: 256Mi