on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acr26025.azurecr.io
        username: ${{ secrets.acr_acr26025_username }}
        password: ${{ secrets.acr_acr26025_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/src" -f  "src/OktaSampleApi/Dockerfile" -t acr26025.azurecr.io/aksworkshop9986:${{ github.sha }}
        docker push acr26025.azurecr.io/aksworkshop9986:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksworkshop9986_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep oktapoc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace oktapoc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: oktapoc
        container-registry-url: acr26025.azurecr.io
        container-registry-username: ${{ secrets.acr_acr26025_username }}
        container-registry-password: ${{ secrets.acr_acr26025_password }}
        secret-name: aksworkshop9dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: oktapoc
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acr26025.azurecr.io/aksworkshop9986:${{ github.sha }}
        imagepullsecrets: |
          aksworkshop9dockerauth